-- Add new LibraryType enum values for module-specific document libraries
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'DAT_SACH_GDN';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'DAT_SACH_PCDI';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'DAT_SACH_QD';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'DUTOAN_TT';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'DUTOAN_QD';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'KHLCNT';
ALTER TYPE "LibraryType" ADD VALUE IF NOT EXISTS 'LCNT_STEP';
