import { Controller, Get, Post, Patch, Body, Param, Query, UseGuards, Request } from '@nestjs/common';
import { DatSachService } from './dat-sach.service';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { RolesGuard } from '../auth/roles.guard';
import { Roles } from '../auth/roles.decorator';
import { Role } from '@prisma/client';
import { JwtService } from '@nestjs/jwt';
import * as fs from 'fs';
import * as path from 'path';
const AdmZip = require('adm-zip');

// ─── Template-based DOCX Generator (inline) ──────────────────────────────────────
// Simple and reliable: replaces {{key}} directly in <w:t> elements.
// Works perfectly with templates generated by the docx library (all placeholders in single runs).

function replacePlaceholdersInXML(content: string, replacements: Record<string, string>): string {
  let result = content;
  for (const [key, value] of Object.entries(replacements)) {
    const cleanKey = key.replace(/\s/g, '');
    const escaped = cleanKey.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Match {{key}} with optional spaces inside braces, case-sensitive
    const placeholder = new RegExp('\\{\\{\\s*' + escaped + '\\s*\\}\\}', 'g');
    // Escape XML special chars in the replacement value
    const xmlValue = String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
    result = result.replace(placeholder, xmlValue);
  }
  return result;
}

function generateFromTemplate(templatePath: string, replacements: Record<string, string>): Buffer {
  const zip = new AdmZip(templatePath);
  const zipEntries = zip.getEntries();
  let docContent = '';
  for (const entry of zipEntries) {
    if (entry.entryName === 'word/document.xml') {
      docContent = entry.getData().toString('utf8');
    }
  }
  if (!docContent) throw new Error('word/document.xml not found in template: ' + templatePath);
  const newDocContent = replacePlaceholdersInXML(docContent, replacements);
  zip.updateFile('word/document.xml', Buffer.from(newDocContent, 'utf8'));
  return zip.toBuffer();
}

// ─── Shared replacement builders ─────────────────────────────────────────────────────

function buildGDNReplacements(data: any, totalSL: number = 0): Record<string, string> {
  return {
    Ngay: data.ngay || data.Ngay || '',
    Thang: data.thang || data.Thang || '',
    Nam: data.nam || data.Nam || new Date().getFullYear().toString(),
    CoQuan: data.coQuan || data.CoQuan || 'Nhà xuất bản Chính trị Quốc gia Sự thật',
    CanCu: data.canCu || data.CanCu || 'Quy chế làm việc của NXB',
    VeViec: data.veViec || data.VeViec || 'Đề nghị in/tái bản sách',
    TenSach: data.tenSach || data.TenSach || '',
    TacGia: data.tacGia || data.TacGia || '',
    BBT: data.bbt || data.BBT || '',
    NamXB: data.namXB || data.NamXB || '',
    SoTrang: data.soTrang || data.SoTrang || '',
    KhoSach: data.khoSach || data.KhoSach || '',
    GiaBia: data.giaBia || data.GiaBia || '',
    SoLuongTon: String(data.soLuongTon ?? ''),
    SLDeNghiIn: totalSL ? String(totalSL) : (data.slDeNghiIn || data.SLDeNghiIn || ''),
    ThoiGianCanSach: data.thoiGianCanSach || data.ThoiGianCanSach || '',
    DeNghiNoiIn: data.deNghiNoiIn || data.DeNghiNoiIn || '',
    GhiChu: data.ghiChu || data.GhiChu || '',
    VuKHTKBT: data.vuKHTKBT || data.VuKHTKBT || '',
    BanBienTap: data.banBienTap || data.BanBienTap || '',
  };
}

function buildPCDIReplacements(data: any): Record<string, string> {
  return {
    SoPhieu: data.soPhieu || data.SoPhieu || '01',
    Ngay: data.ngay || data.Ngay || '',
    Thang: data.thang || data.Thang || '',
    Nam: data.nam || data.Nam || new Date().getFullYear().toString(),
    CoQuan: data.coQuan || data.CoQuan || 'Nhà xuất bản Chính trị Quốc gia Sự thật',
    BBT: data.bbt || data.BBT || '',
    PhuongThuc: data.phuongThuc || data.PhuongThuc || '',
    TenSach: data.tenSach || data.TenSach || '',
    TacGia: data.tacGia || data.TacGia || '',
    SoTrang: data.soTrang || data.SoTrang || '',
    KhoSach: data.khoSach || data.KhoSach || '',
    SoLuongIn: String(data.soLuongIn ?? ''),
    GiaTriHopDong: data.giaTriHopDong || data.GiaTriHopDong || '',
    CoSoIn: data.coSoIn || data.CoSoIn || '',
    ThongSoKyThuat: data.thongSoKyThuat || data.ThongSoKyThuat || '',
    KyTen: data.kyTen || data.KyTen || '',
    ThuTruongDonVi: data.thuTruongDonVi || data.ThuTruongDonVi || '',
  };
}

function buildQDReplacements(data: any): Record<string, string> {
  return {
    Ngay: data.ngay || data.Ngay || '',
    Thang: data.thang || data.Thang || '',
    Nam: data.nam || data.Nam || new Date().getFullYear().toString(),
    SoQuyetDinh: data.soQuyetDinh || data.SoQuyetDinh || '',
    VeViec: data.veViec || data.VeViec || 'V/v in/tái bản sách',
    TacGia: data.tacGia || data.TacGia || '',
    NgonNgu: data.ngonNgu || data.NgonNgu || '',
    khuonKho: data.khuonKho || data.KhuonKho || '',
    SoTrangCuaXuatBanPhamIn: data.soTrangCuaXuatBanPhamIn || data.SoTrangCuaXuatBanPhamIn || data.soTrang || data.SoTrang || '',
    SoLuongIn: String(data.soLuongIn ?? ''),
    DoiTacLienKetXuatBan: data.doiTacLienKet || data.doiTacLienKetXuatBan || '',
    TenBienTapVien: data.tenBienTapVien || data.TenBienTapVien || '',
    CoSoIn: data.coSoIn || data.CoSoIn || '',
    MaSoCachTieuChuanQuocTeISBN: data.isbn || data.ISBN || data.maSoISBN || '',
    TongGiamDoc: data.tongGiamDoc || data.TongGiamDoc || '',
  };
}

// ─── Controller ───────────────────────────────────────────────────────────────────

@Controller('dat-sach')
@UseGuards(JwtAuthGuard, RolesGuard)
export class DatSachController {
  constructor(
    private readonly datSachService: DatSachService,
    private readonly jwtService: JwtService,
  ) {}

  // ─── Projects ───────────────────────────────────────────────

  @Get('projects')
  async getProjects(@Query('parentId') parentId: string) {
    return this.datSachService.getProjectsByParent(parentId);
  }

  @Get('projects/:id')
  async getProject(@Param('id') id: string) {
    return this.datSachService.getProject(id);
  }

  @Post('projects')
  async createProject(
    @Body() body: { parentId?: string; tenDuAn: string; procurementType: string; projectId?: string },
    @Request() req: any,
  ) {
    return this.datSachService.createProject(
      body.parentId || 'project-based',
      body.tenDuAn,
      body.procurementType as any,
      req.user.userId,
      body.projectId,
    );
  }

  @Patch('projects/:id/complete')
  async markCompleted(@Param('id') id: string) {
    return this.datSachService.markProjectCompleted(id);
  }

  // ─── GDN In Sách ───────────────────────────────────────────

  @Post('gdn')
  async createGDN(
    @Body() body: { projectId: string; data: any },
    @Request() req: any,
  ) {
    return this.datSachService.createGDNInSach(body.projectId, body.data, req.user.userId);
  }

  @Patch('gdn/:id')
  async updateGDN(
    @Param('id') id: string,
    @Body() body: { data: any },
  ) {
    return this.datSachService.updateGDNInSach(id, body.data);
  }

  @Post('gdn/:id/assign')
  async assignUsers(
    @Param('id') id: string,
    @Body() body: { userIds: string[] },
    @Request() req: any,
  ) {
    return this.datSachService.assignUsersForSL(id, body.userIds, req.user.userId);
  }

  @Patch('gdn/:id/fill-sl')
  async fillSL(
    @Param('id') id: string,
    @Body() body: { soLuong: number },
    @Request() req: any,
  ) {
    return this.datSachService.fillSL(id, req.user.userId, body.soLuong);
  }

  @Post('gdn/:id/approve')
  @Roles(Role.ADMIN, Role.HEAD_OF_DEPARTMENT, Role.DIRECTOR)
  async approveGDN(@Param('id') id: string) {
    return this.datSachService.approveGDN(id);
  }

  @Get('gdn/:id/download')
  async downloadGDN(@Param('id') id: string, @Request() req: any) {
    const gdn = await this.datSachService['prisma'].gDNInSach.findUnique({
      where: { id },
      include: { assignments: true },
    });
    if (!gdn) throw new (require('@nestjs/common').NotFoundException)('Không tìm thấy GDN');

    const data: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const totalSL = (data.assignments || []).reduce((sum: number, a: any) => sum + (a.soLuong || 0), 0);
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/giay_de_nghi_in.docx');
    const replacements = buildGDNReplacements(data, totalSL);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `GiayDeNghiIn_${gdn.id.slice(0, 8)}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── PCDI Cơ Sở In ─────────────────────────────────────────

  @Post('pcdi')
  async createPCDI(
    @Body() body: { projectId: string; data: any },
    @Request() req: any,
  ) {
    return this.datSachService.createPCDI(body.projectId, body.data, req.user.userId);
  }

  @Patch('pcdi/:id')
  async updatePCDI(
    @Param('id') id: string,
    @Body() body: { data: any },
  ) {
    return this.datSachService.updatePCDI(id, body.data);
  }

  @Post('pcdi/:id/approve')
  @Roles(Role.ADMIN, Role.HEAD_OF_DEPARTMENT, Role.DIRECTOR)
  async approvePCDI(@Param('id') id: string) {
    return this.datSachService.approvePCDI(id);
  }

  @Get('pcdi/:id/download')
  async downloadPCDI(@Param('id') id: string, @Request() req: any) {
    const pcdi = await this.datSachService['prisma'].pCDICoSoIn.findUnique({ where: { id } });
    if (!pcdi) throw new (require('@nestjs/common').NotFoundException)('Không tìm thấy PCDI');

    const data: any = pcdi.data as object;
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/phieu_chi_dinh_co_so_in.docx');
    const replacements = buildPCDIReplacements(data);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `PhieuChiDinhCoSoIn_${pcdi.id.slice(0, 8)}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Patch('project/:id/qd')
  async saveQdData(@Param('id') id: string, @Body() body: { qdData: any }) {
    return this.datSachService.saveQdData(id, body.qdData);
  }

  @Post('project/:id/approve-qd')
  @Roles(Role.ADMIN, Role.HEAD_OF_DEPARTMENT, Role.DIRECTOR)
  async approveQD(@Param('id') id: string) {
    return this.datSachService.approveQD(id);
  }

  @Get('project/:id/download-qd')
  async downloadQD(@Param('id') id: string, @Request() req: any) {
    const project = await this.datSachService.getProjectForGenerate(id);
    const pcdi = project.pcdiDocuments[0];
    // Merge pcdi data and qd data — qdData may contain merged pcdi fields
    const qdData: any = project.qdData as object || {};
    const pcdiData: any = pcdi ? (pcdi.data as object) : {};
    // Prefer qdData for shared fields, fallback to pcdiData
    const templateData = { ...pcdiData, ...qdData };
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(templateData);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`;
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── My Assignments ─────────────────────────────────────────

  @Get('my-assignments')
  async getMyAssignments(@Request() req: any) {
    return this.datSachService.getMyAssignments(req.user.userId);
  }

  // ─── OnlyOffice Config ──────────────────────────────────────
  @Get('gdn/:id/onlyoffice-config')
  async getOnlyofficeConfigForGdn(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForGdn(id);
  }

  @Get('pcdi/:id/onlyoffice-config')
  async getOnlyofficeConfigForPcdi(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForPcdi(id);
  }

  @Get('project/:id/onlyoffice-config')
  async getOnlyofficeConfigForQD(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForQD(id);
  }

  // ─── Public Download (for OnlyOffice) ────────────────────────
  @Get('gdn/:id/download-public')
  async downloadGDNPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    this.datSachService['prisma'].$transaction;
    const AdmZip = require('adm-zip');
    try {
      const payload = this.jwtService.verify(token);
      if (payload.gdnId !== id || payload.purpose !== 'download') {
        throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ');
      }
    } catch {
      throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ hoặc đã hết hạn');
    }

    const gdn = await this.datSachService['prisma'].gDNInSach.findUnique({
      where: { id },
      include: { assignments: true },
    });
    if (!gdn) throw new (require('@nestjs/common').NotFoundException)('Không tìm thấy GDN');

    const data: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const totalSL = (data.assignments || []).reduce((sum: number, a: any) => sum + (a.soLuong || 0), 0);
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/giay_de_nghi_in.docx');
    const replacements = buildGDNReplacements(data, totalSL);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''GiayDeNghiIn_${gdn.id.slice(0, 8)}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Get('pcdi/:id/download-public')
  async downloadPCDIPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    try {
      const payload = this.jwtService.verify(token);
      if (payload.pcdiId !== id || payload.purpose !== 'download') {
        throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ');
      }
    } catch {
      throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ hoặc đã hết hạn');
    }

    const pcdi = await this.datSachService['prisma'].pCDICoSoIn.findUnique({ where: { id } });
    if (!pcdi) throw new (require('@nestjs/common').NotFoundException)('Không tìm thấy PCDI');

    const data: any = pcdi.data as object;
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/phieu_chi_dinh_co_so_in.docx');
    const replacements = buildPCDIReplacements(data);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''PhieuChiDinhCoSoIn_${pcdi.id.slice(0, 8)}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Get('project/:id/download-qd-public')
  async downloadQDPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    try {
      const payload = this.jwtService.verify(token);
      if (payload.projectId !== id || payload.purpose !== 'download') {
        throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ');
      }
    } catch {
      throw new (require('@nestjs/common').ForbiddenException)('Token không hợp lệ hoặc đã hết hạn');
    }

    const project = await this.datSachService.getProjectForGenerate(id);
    const pcdi = project.pcdiDocuments[0];
    const qdData: any = project.qdData as object || {};
    const pcdiData: any = pcdi ? (pcdi.data as object) : {};
    const templateData = { ...pcdiData, ...qdData };
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(templateData);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── Auto-fill Endpoints ───────────────────────────────────

  @Get('project/:projectId/auto-fill/pcdi')
  async getAutoFillForPCDI(@Param('projectId') projectId: string) {
    const data = await this.datSachService.getAutoFillForPCDI(projectId);
    if (!data) {
      throw new (require('@nestjs/common').BadRequestException)(
        'Cần hoàn thành và duyệt GDN trước khi auto-fill PCDI',
      );
    }
    return data;
  }

  @Get('project/:projectId/auto-fill/dutoan')
  async getAutoFillForDutoan(@Param('projectId') projectId: string) {
    const data = await this.datSachService.getAutoFillForDutoan(projectId);
    if (!data) {
      throw new (require('@nestjs/common').BadRequestException)(
        'Cần hoàn thành và duyệt GDN trước khi auto-fill Dự toán',
      );
    }
    return data;
  }

  @Get('project/:projectId/auto-fill/khlcnt')
  async getAutoFillForKHLcnt(@Param('projectId') projectId: string) {
    return this.datSachService.getAutoFillForKHLcnt(projectId);
  }

  // ─── Generate Quyết Định ───────────────────────────────────

  @Get('project/:id/generate')
  async generateQuyetDinh(@Param('id') id: string, @Request() req: any) {
    const project = await this.datSachService.getProjectForGenerate(id);
    const gdn = project.gdnDocuments[0];
    const pcdi = project.pcdiDocuments[0];
    if (!gdn || !pcdi) {
      throw new (require('@nestjs/common').BadRequestException)(
        'Cần hoàn thành GDN và PCDI trước khi generate Quyết định',
      );
    }

    const gdnData: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const pcdiData: any = pcdi.data as object;
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(pcdiData);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }
}
