import { Controller, Get, Post, Patch, Body, Param, Query, UseGuards, Request, BadRequestException, NotFoundException, ForbiddenException } from '@nestjs/common';
import { DatSachService } from './dat-sach.service';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { RolesGuard } from '../auth/roles.guard';
import { Roles } from '../auth/roles.decorator';
import { JwtService } from '@nestjs/jwt';
import { Public } from '../auth/public.decorator';
import * as fs from 'fs';
import * as path from 'path';
const AdmZip = require('adm-zip');

// ─── Template-based DOCX Generator (inline) ──────────────────────────────────────
// Simple and reliable: replaces {{key}} directly in <w:t> elements.
// Works perfectly with templates generated by the docx library (all placeholders in single runs).

function cleanXmlPlaceholders(xml: string): string {
  let result = xml;

  // 1. Merge split braces: { ... { -> {{ and } ... } -> }}
  result = result.replace(/\{[^{}]*?\{/g, (match) => {
    const stripped = match.replace(/<[^>]*>/g, '').replace(/\s/g, '');
    return stripped === '{{' ? '{{' : match;
  });
  result = result.replace(/\}[^{}]*?\}/g, (match) => {
    const stripped = match.replace(/<[^>]*>/g, '').replace(/\s/g, '');
    return stripped === '}}' ? '}}' : match;
  });

  // 2. Strip tags and spaces inside {{ ... }}
  let output = '';
  let currentIndex = 0;
  while (true) {
    const startIndex = result.indexOf('{{', currentIndex);
    if (startIndex === -1) {
      output += result.substring(currentIndex);
      break;
    }
    output += result.substring(currentIndex, startIndex);
    
    const endIndex = result.indexOf('}}', startIndex);
    if (endIndex === -1) {
      output += result.substring(startIndex);
      break;
    }

    const content = result.substring(startIndex, endIndex + 2);
    // Strip XML tags AND all spaces inside the placeholder name
    const cleanContent = content.replace(/<[^>]*>/g, '').replace(/\s/g, '');
    output += cleanContent;

    currentIndex = endIndex + 2;
  }
  return output;
}

function replacePlaceholdersInXML(content: string, replacements: Record<string, string>): string {
  let result = cleanXmlPlaceholders(content);
  for (const [key, value] of Object.entries(replacements)) {
    const cleanKey = key.replace(/\s/g, '');
    const escaped = cleanKey.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Match {{key}} case-insensitively, allowing no spaces (since cleanXmlPlaceholders strips them)
    const placeholder = new RegExp('\\{\\{' + escaped + '\\}\\}', 'gi');
    // Escape XML special chars in the replacement value
    const xmlValue = String(value ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
    result = result.replace(placeholder, xmlValue);
  }
  return result;
}

function generateFromTemplate(templatePath: string, replacements: Record<string, string>): Buffer {
  const zip = new AdmZip(templatePath);
  const zipEntries = zip.getEntries();
  let docContent = '';
  for (const entry of zipEntries) {
    if (entry.entryName === 'word/document.xml') {
      docContent = entry.getData().toString('utf8');
    }
  }
  if (!docContent) throw new Error('word/document.xml not found in template: ' + templatePath);
  const newDocContent = replacePlaceholdersInXML(docContent, replacements);
  zip.updateFile('word/document.xml', Buffer.from(newDocContent, 'utf8'));
  return zip.toBuffer();
}

// ─── Shared replacement builders ─────────────────────────────────────────────────────

function buildGDNReplacements(data: any, totalSL: number = 0): Record<string, string> {
  const today = new Date();
  const defaultNgay = String(today.getDate()).padStart(2, '0');
  const defaultThang = String(today.getMonth() + 1).padStart(2, '0');
  const defaultNam = String(today.getFullYear());

  return {
    Ngay: data.ngay || data.Ngay || defaultNgay,
    Thang: data.thang || data.Thang || defaultThang,
    Nam: data.nam || data.Nam || defaultNam,
    CoQuan: data.coQuan || data.CoQuan || 'Nhà xuất bản Chính trị Quốc gia Sự thật',
    CanCu: data.canCu || data.CanCu || 'Quy chế làm việc của NXB',
    VeViec: data.veViec || data.VeViec || 'Đề nghị in/tái bản sách',
    TenSach: data.tenSach || data.TenSach || '',
    TacGia: data.tacGia || data.TacGia || '',
    BBT: data.bbt || data.BBT || '',
    NamXB: data.namXB || data.NamXB || '',
    SoTrang: data.soTrang || data.SoTrang || '',
    KhoSach: data.khoSach || data.KhoSach || '',
    GiaBia: data.giaBia || data.GiaBia || '',
    SoLuongTon: String(data.soLuongTon ?? ''),
    SLDeNghiIn: totalSL ? String(totalSL) : (data.slDeNghiIn || data.SLDeNghiIn || ''),
    ThoiGianCanSach: data.thoiGianCanSach || data.ThoiGianCanSach || '',
    DeNghiNoiIn: data.deNghiNoiIn || data.DeNghiNoiIn || '',
    GhiChu: data.ghiChu || data.GhiChu || '',
    VuKHTKBT: data.vuKHTKBT || data.VuKHTKBT || '',
    BanBienTap: data.banBienTap || data.BanBienTap || '',
  };
}

function buildPCDIReplacements(data: any): Record<string, string> {
  const today = new Date();
  const defaultNgay = String(today.getDate()).padStart(2, '0');
  const defaultThang = String(today.getMonth() + 1).padStart(2, '0');
  const defaultNam = String(today.getFullYear());

  return {
    SoPhieu: data.soPhieu || data.SoPhieu || '01',
    Ngay: data.ngay || data.Ngay || defaultNgay,
    Thang: data.thang || data.Thang || defaultThang,
    Nam: data.nam || data.Nam || defaultNam,
    CoQuan: data.coQuan || data.CoQuan || 'Nhà xuất bản Chính trị Quốc gia Sự thật',
    BBT: data.bbt || data.BBT || '',
    PhuongThuc: data.phuongThuc || data.PhuongThuc || '',
    TenSach: data.tenSach || data.TenSach || '',
    TacGia: data.tacGia || data.TacGia || '',
    SoTrang: data.soTrang || data.SoTrang || '',
    KhoSach: data.khoSach || data.KhoSach || '',
    SoLuongIn: String(data.soLuongIn ?? ''),
    GiaTriHopDong: data.giaTriHopDong || data.GiaTriHopDong || '',
    CoSoIn: data.coSoIn || data.CoSoIn || '',
    ThongSoKyThuat: data.thongSoKyThuat || data.ThongSoKyThuat || '',
    KyTen: data.kyTen || data.KyTen || '',
    ThuTruongDonVi: data.thuTruongDonVi || data.ThuTruongDonVi || '',
  };
}

function buildQDReplacements(data: any): Record<string, string> {
  const today = new Date();
  const defaultNgay = String(today.getDate()).padStart(2, '0');
  const defaultThang = String(today.getMonth() + 1).padStart(2, '0');
  const defaultNam = String(today.getFullYear());

  return {
    Ngay: data.ngay || data.Ngay || data.ngayBanHanh || defaultNgay,
    Thang: data.thang || data.Thang || data.thangBanHanh || defaultThang,
    Nam: data.nam || data.Nam || data.namBanHanh || defaultNam,
    So: data.soQuyetDinh || data.SoQuyetDinh || '',
    SoQuyetDinh: data.soQuyetDinh || data.SoQuyetDinh || '',
    VeViec: data.veViec || data.VeViec || 'V/v in/tái bản sách',
    TacGia: data.tacGia || data.TacGia || '',
    NgonNgu: data.ngonNgu || data.NgonNgu || '',
    khuonKho: data.khuonKho || data.KhuonKho || '',
    SoTrangCuaXuatBanPhamIn: data.soTrangCuaXuatBanPhamIn || data.SoTrangCuaXuatBanPhamIn || data.soTrang || data.SoTrang || '',
    SoLuongIn: String(data.soLuongIn ?? ''),
    DoiTacLienKetXuatBan: data.doiTacLienKet || data.doiTacLienKetXuatBan || '',
    TenBienTapVien: data.tenBienTapVien || data.TenBienTapVien || '',
    CoSoIn: data.coSoIn || data.CoSoIn || '',
    'MaSoCachTieuChuanQuocTe - ISBN': data.isbn || data.ISBN || data.maSoISBN || '',
    MaSoCachTieuChuanQuocTeISBN: data.isbn || data.ISBN || data.maSoISBN || '',
    TongGiamDoc: data.tongGiamDoc || data.TongGiamDoc || '',
  };
}

// ─── Controller ───────────────────────────────────────────────────────────────────

@Controller('dat-sach')
@UseGuards(JwtAuthGuard, RolesGuard)
export class DatSachController {
  constructor(
    private readonly datSachService: DatSachService,
    private readonly jwtService: JwtService,
  ) {}

  // ─── Projects ───────────────────────────────────────────────

  @Get('projects')
  async getProjects(@Query('parentId') parentId: string) {
    return this.datSachService.getProjectsByParent(parentId);
  }

  @Get('projects/:id')
  async getProject(@Param('id') id: string) {
    return this.datSachService.getProject(id);
  }

  @Post('projects')
  async createProject(
    @Body() body: { parentId?: string; tenDuAn: string; procurementType: string; projectId?: string },
    @Request() req: any,
  ) {
    return this.datSachService.createProject(
      body.parentId || 'project-based',
      body.tenDuAn,
      body.procurementType as any,
      req.user.userId,
      body.projectId,
    );
  }

  @Patch('projects/:id/complete')
  async markCompleted(@Param('id') id: string) {
    return this.datSachService.markProjectCompleted(id);
  }

  // ─── GDN In Sách ───────────────────────────────────────────

  @Post('gdn')
  async createGDN(
    @Body() body: { projectId: string; data: any },
    @Request() req: any,
  ) {
    return this.datSachService.createGDNInSach(body.projectId, body.data, req.user.userId);
  }

  @Patch('gdn/:id')
  async updateGDN(
    @Param('id') id: string,
    @Body() body: { data: any },
  ) {
    return this.datSachService.updateGDNInSach(id, body.data);
  }

  @Post('gdn/:id/assign')
  async assignUsers(
    @Param('id') id: string,
    @Body() body: { userIds: string[] },
    @Request() req: any,
  ) {
    return this.datSachService.assignUsersForSL(id, body.userIds, req.user.userId);
  }

  @Patch('gdn/:id/fill-sl')
  async fillSL(
    @Param('id') id: string,
    @Body() body: { soLuong: number },
    @Request() req: any,
  ) {
    return this.datSachService.fillSL(id, req.user.userId, body.soLuong);
  }

  // ─── Review Workflow ──────────────────────────────────────────

  @Post('gdn/:id/submit-review')
  async submitGDNForReview(
    @Param('id') id: string,
    @Body() body: { reviewerId: string },
    @Request() req: any,
  ) {
    return this.datSachService.submitGDNForReview(id, body.reviewerId, req.user.userId);
  }

  @Post('gdn/:id/review-approve')
  async approveGDNReview(
    @Param('id') id: string,
    @Body() body: { comment?: string },
    @Request() req: any,
  ) {
    return this.datSachService.approveGDNReview(id, req.user.userId, body.comment);
  }

  @Post('gdn/:id/review-rework')
  async reworkGDN(
    @Param('id') id: string,
    @Body() body: { comment: string },
    @Request() req: any,
  ) {
    return this.datSachService.reworkGDN(id, req.user.userId, body.comment);
  }

  @Post('pcdi/:id/submit-review')
  async submitPCDIForReview(
    @Param('id') id: string,
    @Body() body: { reviewerId: string },
    @Request() req: any,
  ) {
    return this.datSachService.submitPCDIForReview(id, body.reviewerId, req.user.userId);
  }

  @Post('pcdi/:id/review-approve')
  async approvePCDIReview(
    @Param('id') id: string,
    @Body() body: { comment?: string },
    @Request() req: any,
  ) {
    return this.datSachService.approvePCDIReview(id, req.user.userId, body.comment);
  }

  @Post('pcdi/:id/review-rework')
  async reworkPCDI(
    @Param('id') id: string,
    @Body() body: { comment: string },
    @Request() req: any,
  ) {
    return this.datSachService.reworkPCDI(id, req.user.userId, body.comment);
  }

  @Post('project/:id/submit-review')
  async submitQDForReview(
    @Param('id') id: string,
    @Body() body: { reviewerId: string },
    @Request() req: any,
  ) {
    return this.datSachService.submitQDForReview(id, body.reviewerId, req.user.userId);
  }

  @Post('project/:id/review-approve')
  async approveQDReview(
    @Param('id') id: string,
    @Body() body: { comment?: string },
    @Request() req: any,
  ) {
    return this.datSachService.approveQDReview(id, req.user.userId, body.comment);
  }

  @Post('project/:id/review-rework')
  async reworkQD(
    @Param('id') id: string,
    @Body() body: { comment: string },
    @Request() req: any,
  ) {
    return this.datSachService.reworkQD(id, req.user.userId, body.comment);
  }

  @Get('my-pending-reviews')
  getPendingReviews(@Request() req: any) {
    return this.datSachService.getPendingReviews(req.user.userId);
  }

  // ─── Download / Generate ──────────────────────────────────────

  @Get('gdn/:id/download')
  async downloadGDN(@Param('id') id: string, @Request() req: any) {
    const gdn = await this.datSachService['prisma'].gDNInSach.findUnique({
      where: { id },
      include: { assignments: true },
    });
    if (!gdn) throw new NotFoundException('Không tìm thấy GDN');

    const data: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const totalSL = (data.assignments || []).reduce((sum: number, a: any) => sum + (a.soLuong || 0), 0);
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/giay_de_nghi_in.docx');
    const replacements = buildGDNReplacements(data, totalSL);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `GiayDeNghiIn_${gdn.id.slice(0, 8)}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── PCDI Cơ Sở In ─────────────────────────────────────────

  @Post('pcdi')
  async createPCDI(
    @Body() body: { projectId: string; data: any },
    @Request() req: any,
  ) {
    return this.datSachService.createPCDI(body.projectId, body.data, req.user.userId);
  }

  @Patch('pcdi/:id')
  async updatePCDI(
    @Param('id') id: string,
    @Body() body: { data: any },
  ) {
    return this.datSachService.updatePCDI(id, body.data);
  }

  @Get('pcdi/:id/download')
  async downloadPCDI(@Param('id') id: string, @Request() req: any) {
    const pcdi = await this.datSachService['prisma'].pCDICoSoIn.findUnique({ where: { id } });
    if (!pcdi) throw new NotFoundException('Không tìm thấy PCDI');

    const data: any = pcdi.data as object;
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/phieu_chi_dinh_co_so_in.docx');
    const replacements = buildPCDIReplacements(data);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `PhieuChiDinhCoSoIn_${pcdi.id.slice(0, 8)}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Patch('project/:id/qd')
  async saveQdData(@Param('id') id: string, @Body() body: { qdData: any }) {
    return this.datSachService.saveQdData(id, body.qdData);
  }

  @Get('project/:id/download-qd')
  async downloadQD(@Param('id') id: string, @Request() req: any) {
    const project = await this.datSachService.getProjectForGenerate(id);
    const gdn = project.gdnDocuments?.[0];
    const pcdi = project.pcdiDocuments?.[0];
    const qdData: any = project.qdData as object || {};
    const gdnData: any = gdn ? { ...(gdn.data as object), assignments: gdn.assignments } : {};
    const pcdiData: any = pcdi ? (pcdi.data as object) : {};
    const templateData = { ...gdnData, ...pcdiData, ...qdData };
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(templateData);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`;
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── My Assignments ─────────────────────────────────────────

  @Get('my-assignments')
  async getMyAssignments(@Request() req: any) {
    return this.datSachService.getMyAssignments(req.user.userId);
  }

  // ─── OnlyOffice Config ──────────────────────────────────────
  @Get('gdn/:id/onlyoffice-config')
  async getOnlyofficeConfigForGdn(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForGdn(id);
  }

  @Get('pcdi/:id/onlyoffice-config')
  async getOnlyofficeConfigForPcdi(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForPcdi(id);
  }

  @Get('project/:id/onlyoffice-config')
  async getOnlyofficeConfigForQD(@Param('id') id: string) {
    return this.datSachService.getOnlyofficeConfigForQD(id);
  }

  // ─── Public Download (for OnlyOffice) ────────────────────────
  @Public()
  @Get('gdn/:id/download-public')
  async downloadGDNPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    this.datSachService['prisma'].$transaction;
    const AdmZip = require('adm-zip');
    try {
      const payload = this.jwtService.verify(token);
      if (payload.gdnId !== id || payload.purpose !== 'download') {
        throw new ForbiddenException('Token không hợp lệ');
      }
    } catch {
      throw new ForbiddenException('Token không hợp lệ hoặc đã hết hạn');
    }

    const gdn = await this.datSachService['prisma'].gDNInSach.findUnique({
      where: { id },
      include: { assignments: true },
    });
    if (!gdn) throw new NotFoundException('Không tìm thấy GDN');

    const data: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const totalSL = (data.assignments || []).reduce((sum: number, a: any) => sum + (a.soLuong || 0), 0);
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/giay_de_nghi_in.docx');
    const replacements = buildGDNReplacements(data, totalSL);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''GiayDeNghiIn_${gdn.id.slice(0, 8)}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Public()
  @Get('pcdi/:id/download-public')
  async downloadPCDIPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    try {
      const payload = this.jwtService.verify(token);
      if (payload.pcdiId !== id || payload.purpose !== 'download') {
        throw new ForbiddenException('Token không hợp lệ');
      }
    } catch {
      throw new ForbiddenException('Token không hợp lệ hoặc đã hết hạn');
    }

    const pcdi = await this.datSachService['prisma'].pCDICoSoIn.findUnique({ where: { id } });
    if (!pcdi) throw new NotFoundException('Không tìm thấy PCDI');

    const data: any = pcdi.data as object;
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/phieu_chi_dinh_co_so_in.docx');
    const replacements = buildPCDIReplacements(data);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''PhieuChiDinhCoSoIn_${pcdi.id.slice(0, 8)}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  @Public()
  @Get('project/:id/download-qd-public')
  async downloadQDPublic(@Param('id') id: string, @Query('token') token: string, @Request() req: any) {
    try {
      const payload = this.jwtService.verify(token);
      if (payload.projectId !== id || payload.purpose !== 'download') {
        throw new ForbiddenException('Token không hợp lệ');
      }
    } catch {
      throw new ForbiddenException('Token không hợp lệ hoặc đã hết hạn');
    }

    const project = await this.datSachService.getProjectForGenerate(id);
    const gdn = project.gdnDocuments?.[0];
    const pcdi = project.pcdiDocuments?.[0];
    const qdData: any = project.qdData as object || {};
    const gdnData: any = gdn ? { ...(gdn.data as object), assignments: gdn.assignments } : {};
    const pcdiData: any = pcdi ? (pcdi.data as object) : {};
    const templateData = { ...gdnData, ...pcdiData, ...qdData };
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(templateData);
    const buffer = generateFromTemplate(templatePath, replacements);
    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }

  // ─── Auto-fill Endpoints ───────────────────────────────────

  @Get('project/:projectId/auto-fill/pcdi')
  async getAutoFillForPCDI(@Param('projectId') projectId: string) {
    const data = await this.datSachService.getAutoFillForPCDI(projectId);
    if (!data) {
      throw new BadRequestException(
        'Cần tạo và lưu GDN trước khi auto-fill PCDI',
      );
    }
    return data;
  }

  @Get('project/:projectId/auto-fill/dutoan')
  async getAutoFillForDutoan(@Param('projectId') projectId: string) {
    const data = await this.datSachService.getAutoFillForDutoan(projectId);
    if (!data) {
      throw new BadRequestException(
        'Cần hoàn thành và duyệt GDN trước khi auto-fill Dự toán',
      );
    }
    return data;
  }

  @Get('project/:projectId/auto-fill/khlcnt')
  async getAutoFillForKHLcnt(@Param('projectId') projectId: string) {
    return this.datSachService.getAutoFillForKHLcnt(projectId);
  }

  // ─── Generate Quyết Định ───────────────────────────────────

  @Get('project/:id/generate')
  async generateQuyetDinh(@Param('id') id: string, @Request() req: any) {
    const project = await this.datSachService.getProjectForGenerate(id);
    const gdn = project.gdnDocuments?.[0];
    const pcdi = project.pcdiDocuments?.[0];
    if (!gdn || !pcdi) {
      throw new BadRequestException(
        'Cần hoàn thành GDN và PCDI trước khi generate Quyết định',
      );
    }

    const qdData: any = project.qdData as object || {};
    const gdnData: any = { ...(gdn.data as object), assignments: gdn.assignments };
    const pcdiData: any = pcdi.data as object;
    const templateData = { ...gdnData, ...pcdiData, ...qdData };
    const templatePath = path.resolve(process.env.FILEMAU_PATH || '/app/FileMau', 'DatSach/quyet_dinh.docx');
    const replacements = buildQDReplacements(templateData);
    const buffer = generateFromTemplate(templatePath, replacements);
    const filename = `QuyetDinhDatSach_${project.tenDuAn.replace(/[^a-zA-Z0-9]/g, '_')}.docx`;

    req.res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`);
    req.res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    req.res.end(buffer);
  }
}
