import { FieldDef } from '@/components/SmartFormField';

export const CDT_STEP_FIELDS: Record<string, FieldDef[]> = {
  thu_moi_hoan_thien: [
    { key: 'DiaDanh', label: 'Địa danh', group: 'chung' },
    { key: 'NamThucHienHopDong', label: 'Năm thực hiện hợp đồng', group: 'chung' },
    { key: 'TenGoiThau', label: 'Tên gói thầu', group: 'chung' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm', group: 'chung' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư', group: 'cdt' },
    { key: 'TenVietTatChuDauTu', label: 'Tên viết tắt chủ đầu tư', group: 'cdt' },
    { key: 'DonViMoi', label: 'Đơn vị mời', group: 'cdt' },
    { key: 'DaiDien', label: 'Đại diện', group: 'cdt' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện chủ đầu tư', group: 'cdt' },
    { key: 'ChucVu', label: 'Chức vụ', group: 'cdt' },
    { key: 'DiaChiChuDauTu', label: 'Địa chỉ chủ đầu tư', group: 'cdt' },
    { key: 'SoTaiKhoanCDT', label: 'Số tài khoản chủ đầu tư', group: 'cdt' },
    { key: 'TaiNganHang', label: 'Tài ngân hàng', group: 'cdt' },
    { key: 'TenVietTatNhaThau', label: 'Tên viết tắt nhà thầu', group: 'nt' },
    { key: 'NhaThau', label: 'Nhà thầu', group: 'nt' },
    { key: 'DiaChi', label: 'Địa chỉ', group: 'nt' },
    { key: 'MaSoThue', label: 'Mã số thuế', group: 'nt' },
    { key: 'DienThoai', label: 'Điện thoại', group: 'nt' },
    { key: 'SoTaiKhoan', label: 'Số tài khoản', group: 'nt' },
    { key: 'CanCuVanBanPhapLy', label: 'Căn cứ văn bản pháp lý', type: 'textarea', group: 'chung' },
    { key: 'SanPhamGoiThau', label: 'Sản phẩm gói thầu', group: 'chung' },
    { key: 'SoLuong', label: 'Số lượng', group: 'chung' },
    { key: 'SoNgayThucHienHopDong', label: 'Số ngày thực hiện hợp đồng', group: 'chung' },
    { key: 'GiaTriHopDongBangSo', label: 'Giá trị hợp đồng bằng số', type: 'money', group: 'chung' },
    { key: 'GiaTriHopDongBangChu', label: 'Giá trị hợp đồng bằng chữ', type: 'money-words', group: 'chung' },
  ],
  bien_ban_hoan_thien: [
    { key: 'DiaDanh', label: 'Địa danh', group: 'chung' },
    { key: 'Ngay', label: 'Ngày', type: 'date', group: 'chung' },
    { key: 'thang', label: 'Tháng', group: 'chung' },
    { key: 'nam', label: 'Năm', group: 'chung' },
    { key: 'HomNay', label: 'Hôm nay', type: 'date', group: 'chung' },
    { key: 'TenGoiThau', label: 'Tên gói thầu', group: 'chung' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm', group: 'chung' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư', group: 'cdt' },
    { key: 'ChucVu', label: 'Chức vụ', group: 'cdt' },
    { key: 'SoTaiKhoanCDT', label: 'Số tài khoản chủ đầu tư', group: 'cdt' },
    { key: 'NganHangCDT', label: 'Ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaNganHangCDT', label: 'Mã ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaSoThueCDT', label: 'Mã số thuế chủ đầu tư', group: 'cdt' },
    { key: 'DiaChi', label: 'Địa chỉ', group: 'cdt' },
    { key: 'NhaThau', label: 'Nhà thầu', group: 'nt' },
    { key: 'DaiDienNhaThau', label: 'Đại diện nhà thầu', group: 'nt' },
    { key: 'SoDienThoai', label: 'Số điện thoại', group: 'nt' },
    { key: 'SoTaiKhoanNT', label: 'Số tài khoản nhà thầu', group: 'nt' },
    { key: 'NganHangNT', label: 'Ngân hàng nhà thầu', group: 'nt' },
    { key: 'MaNganHangNT', label: 'Mã ngân hàng nhà thầu', group: 'nt' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng', group: 'chung' },
    { key: 'GiaTriHopDongBangSo', label: 'Giá trị hợp đồng bằng số', type: 'money', group: 'chung' },
  ],
  to_trinh_kqlcnt: [
    { key: 'DiaDanh', label: 'Địa danh', group: 'chung' },
    { key: 'DonViTrinh', label: 'Đơn vị trình', group: 'chung' },
    { key: 'TenVietTatDonViTrinh', label: 'Tên viết tắt đơn vị trình', group: 'chung' },
    { key: 'TenGoiThau', label: 'Tên gói thầu', group: 'chung' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm', group: 'chung' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư', group: 'cdt' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện chủ đầu tư', group: 'cdt' },
    { key: 'CanCuVanBanPhapLy', label: 'Căn cứ văn bản pháp lý', type: 'textarea', group: 'chung' },
    { key: 'GiaTriHopDongBangSo', label: 'Giá trị hợp đồng bằng số', type: 'money', group: 'chung' },
    { key: 'GiaTriHopDongBangChu', label: 'Giá trị hợp đồng bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'NguonVon', label: 'Nguồn vốn', group: 'chung' },
    { key: 'ThoiGianLuaChonNhaThau', label: 'Thời gian lựa chọn nhà thầu', group: 'chung' },
    { key: 'ThoiGianBatDauToChucLuaChonNhaThau', label: 'Thời gian bắt đầu tổ chức LCNT', group: 'chung' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng', group: 'chung' },
    { key: 'ThoiGianThucHienGoiThau', label: 'Thời gian thực hiện gói thầu', group: 'chung' },
    { key: 'CoKhongApDung', label: 'Có/Không áp dụng ưu đãi', group: 'chung' },
    { key: 'NhaThau', label: 'Nhà thầu', group: 'nt' },
    { key: 'TenVietTatNhaThau', label: 'Tên viết tắt nhà thầu', group: 'nt' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu', group: 'nt' },
    { key: 'CoQuanCapMaSoThue', label: 'Cơ quan cấp mã số thuế', group: 'nt' },
    { key: 'NgayCapMaSoThueNhaThau', label: 'Ngày cấp MST nhà thầu', type: 'date', group: 'nt' },
    { key: 'DiaChiNhaThau', label: 'Địa chỉ nhà thầu', group: 'nt' },
    { key: 'ThoiGianThucHienHopDong', label: 'Thời gian thực hiện hợp đồng', group: 'chung' },
    { key: 'GhiChuThoiGian', label: 'Ghi chú thời gian', group: 'chung' },
  ],
  quyet_dinh_kqlcnt: [
    { key: 'DiaDanh', label: 'Địa danh' },
    { key: 'TenGoiThau', label: 'Tên gói thầu' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư' },
    { key: 'TenVietTatChuDauTu', label: 'Tên viết tắt chủ đầu tư' },
    { key: 'DonViMoi', label: 'Đơn vị mời' },
    { key: 'DonViTrinh', label: 'Đơn vị trình' },
    { key: 'TenVietTatDonViTrinh', label: 'Tên viết tắt đơn vị trình' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện chủ đầu tư' },
    { key: 'CanCuVanBanPhapLy', label: 'Căn cứ văn bản pháp lý', type: 'textarea' },
    { key: 'NhaThau', label: 'Nhà thầu' },
    { key: 'GiaTriDuToanDuocDuyet', label: 'Giá trị dự toán được duyệt', type: 'money' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng' },
    { key: 'ThoiGianThucHienGoiThau', label: 'Thời gian thực hiện gói thầu' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu' },
    { key: 'GiaTrungThau', label: 'Giá trúng thầu', type: 'money' },
    { key: 'ThoiGianThucHienHopDong', label: 'Thời gian thực hiện hợp đồng' },
  ],
  hop_dong: [
    { key: 'DiaDanh', label: 'Địa danh', group: 'chung' },
    { key: 'MaSoHD', label: 'Mã số hợp đồng', group: 'chung' },
    { key: 'NamKyHD', label: 'Năm ký hợp đồng', group: 'chung' },
    { key: 'TenGoiThau', label: 'Tên gói thầu', group: 'chung' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm', group: 'chung' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư', group: 'cdt' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện chủ đầu tư', group: 'cdt' },
    { key: 'ChucVuDaiDienChuDauTu', label: 'Chức vụ đại diện chủ đầu tư', group: 'cdt' },
    { key: 'DiaChiChuDauTu', label: 'Địa chỉ chủ đầu tư', group: 'cdt' },
    { key: 'SoDienThoaiChuDauTu', label: 'Số điện thoại chủ đầu tư', group: 'cdt' },
    { key: 'SoTaiKhoanChuDauTu', label: 'Số tài khoản chủ đầu tư', group: 'cdt' },
    { key: 'NganHangChuDauTu', label: 'Ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaSoNganHangChuDauTu', label: 'Mã số ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaSoThueChuDauTu', label: 'Mã số thuế chủ đầu tư', group: 'cdt' },
    { key: 'NhaThau', label: 'Nhà thầu', group: 'nt' },
    { key: 'DaiDienNhaThau', label: 'Đại diện nhà thầu', group: 'nt' },
    { key: 'ChucVuDaiDienNhaThau', label: 'Chức vụ đại diện nhà thầu', group: 'nt' },
    { key: 'DiaChiNhaThau', label: 'Địa chỉ nhà thầu', group: 'nt' },
    { key: 'SoDienThoaiNhaThau', label: 'Số điện thoại nhà thầu', group: 'nt' },
    { key: 'SoTaiKhoanNhaThau', label: 'Số tài khoản nhà thầu', group: 'nt' },
    { key: 'NganHangNhaThau', label: 'Ngân hàng nhà thầu', group: 'nt' },
    { key: 'MaSoNganHangNhaThau', label: 'Mã số ngân hàng nhà thầu', group: 'nt' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu', group: 'nt' },
    { key: 'TenQuyetDinhPheDuyetKeHoachLuaChonNhaThau', label: 'Tên quyết định phê duyệt KHLCNT', group: 'chung' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng', group: 'chung' },
    { key: 'GiaHDBangSo', label: 'Giá HĐ bằng số', type: 'money', group: 'chung' },
    { key: 'GiaHDBangChu', label: 'Giá HĐ bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'ThoiGianThucHienHD', label: 'Thời gian thực hiện hợp đồng', group: 'chung' },
  ],
};

export const CHCT_STEP_FIELDS: Record<string, FieldDef[]> = {
  to_trinh_hsmt: [
    { key: 'tendonvicuatochuyengia', label: 'Tên tổ chức, đơn vị' },
    { key: 'MaSoToTrinhPheDuyetHSMT', label: 'Mã số tờ trình phê duyệt HSMT' },
    { key: 'ĐiaDanh', label: 'Địa danh' },
    { key: 'TenGoiThau', label: 'Tên gói thầu' },
    { key: 'TenKeHoachLuaChonNhaThau', label: 'Tên kế hoạch lựa chọn nhà thầu' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm' },
    { key: 'TenChuDauTu', label: 'Tên chủ đầu tư' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư' },
    { key: 'TenQuyetDinhPheDuyetKeHoachLuaChonNhaThau', label: 'Tên quyết định phê duyệt KHLCNT' },
    { key: 'TenCacVanBanPhapLyLienQuan', label: 'Tên các văn bản pháp lý liên quan', type: 'textarea' },
    { key: 'GiaGoiThauBangSo', label: 'Giá gói thầu bằng số', type: 'money' },
    { key: 'GiaGoiThauBangChu', label: 'Giá gói thầu bằng chữ', type: 'money-words' },
    { key: 'NguonVon', label: 'Nguồn vốn' },
    { key: 'ThoiGianToChucLuaChonNhaThau', label: 'Thời gian tổ chức lựa chọn nhà thầu' },
    { key: 'ThoiGianBatDauToChucLuaChonNhaThau', label: 'Thời gian bắt đầu tổ chức LCNT' },
    { key: 'HinhThucPhuongThucLuaChonNhaThau', label: 'Hình thức/phương thức LCNT' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng' },
    { key: 'ThoiGianThucHienGoiThau', label: 'Thời gian thực hiện gói thầu' },
    { key: 'TuyChonMuaThem', label: 'Tùy chọn mua thêm' },
    { key: 'ChuDauTu/DonViTuVanDauThau', label: 'CĐT/đơn vị tư vấn đấu thầu' },
    { key: 'MaSoQuyetDinhLapHSMT', label: 'Mã số quyết định lập HSMT' },
    { key: 'MaSoHD', label: 'Mã số hợp đồng' },
    { key: 'ThoiGianKyHĐ', label: 'Thời gian ký hợp đồng', type: 'date' },
    { key: 'TenDonViTuVanDauThau', label: 'Tên đơn vị tư vấn đấu thầu' },
    { key: 'STT', label: 'STT' },
    { key: 'HoVaTenThanhVienTCG', label: 'Họ và tên thành viên tổ chuyên gia' },
    { key: 'ChucVuTrongTCG', label: 'Chức vụ trong tổ chuyên gia' },
    { key: 'PhanCongCongViec', label: 'Phân công công việc' },
    { key: 'CachThucLamViecCuaToChuyenGia', label: 'Cách thức làm việc của tổ chuyên gia' },
    { key: 'TomTatNoiDungHSMT', label: 'Tóm tắt nội dung HSMT', type: 'textarea' },
    { key: 'YKienBaoLuuTongQuat', label: 'Ý kiến bảo lưu tổng quát', type: 'textarea' },
    { key: 'NoiDungHSMTBaoLuu', label: 'Nội dung HSMT bảo lưu' },
    { key: 'YKienBaoLuu', label: 'Ý kiến bảo lưu' },
    { key: 'LyDoBaoLuu', label: 'Lý do bảo lưu' },
    { key: 'TenChuyenGia1', label: 'Tên chuyên gia 1' },
    { key: 'TenChuyenGia2', label: 'Tên chuyên gia 2' },
    { key: 'TenChuyenGia3', label: 'Tên chuyên gia 3' },
  ],
  quyet_dinh_hsmt: [
    { key: 'TenChuDauTu', label: 'Tên chủ đầu tư' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư' },
    { key: 'TenGoiThau', label: 'Tên gói thầu' },
    { key: 'TenKeHoachLuaChonNhaThau', label: 'Tên kế hoạch lựa chọn nhà thầu' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện theo pháp luật của chủ đầu tư' },
    { key: 'ThoiGianToTrinhPheDuyetHSMT', label: 'Thời gian tờ trình phê duyệt HSMT' },
    { key: 'TenCacVanBanPhapLyLienQuan', label: 'Tên các văn bản pháp lý liên quan', type: 'textarea' },
    { key: 'DonViDuocGiao', label: 'Đơn vị được giao' },
    { key: 'ChucVuDaiDienChuDauTu', label: 'Chức vụ đại diện chủ đầu tư' },
  ],
  to_trinh_kqlcnt: [
    { key: 'SoToTrinh', label: 'Số tờ trình' },
    { key: 'TenQuyetDinhPheDuyetKeHoachLuaChonNhaThau', label: 'Tên quyết định phê duyệt KHLCNT' },
    { key: 'TenQuyetDinhPheDuyetHSMT', label: 'Tên quyết định phê duyệt HSMT' },
    { key: 'TenGoiThau', label: 'Tên gói thầu' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm' },
    { key: 'MaSoBCDG', label: 'Mã số báo cáo đánh giá' },
    { key: 'ThoiGianRaBCDG', label: 'Thời gian ra báo cáo đánh giá' },
    { key: 'DonViLapBCDG', label: 'Đơn vị lập báo cáo đánh giá' },
    { key: 'MaSoBBDCTL', label: 'Mã số biên bản đối chiếu tài liệu' },
    { key: 'ThoiGianRaBBDCTL', label: 'Thời gian ra biên bản đối chiếu' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư' },
    { key: 'NhaThauDuocDoiChieu', label: 'Nhà thầu được đối chiếu' },
    { key: 'GiaGoiThauBangSo', label: 'Giá gói thầu bằng số', type: 'money' },
    { key: 'NguonVon', label: 'Nguồn vốn' },
    { key: 'ThoiGianToChucLuaChonNhaThau', label: 'Thời gian tổ chức lựa chọn nhà thầu' },
    { key: 'ThoiGianBatDauToChucLuaChonNhaThau', label: 'Thời gian bắt đầu tổ chức LCNT' },
    { key: 'HinhThucPhuongThucLuaChonNhaThau', label: 'Hình thức/phương thức LCNT' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng' },
    { key: 'ThoiGianThucHienGoiThau', label: 'Thời gian thực hiện gói thầu' },
    { key: 'TuyChonMuaThem', label: 'Tùy chọn mua thêm' },
    { key: 'STT', label: 'STT' },
    { key: 'TenNhaThauDoiChieu', label: 'Tên nhà thầu đối chiếu' },
    { key: 'DanhGiaTinhHopLe', label: 'Đánh giá tính hợp lệ' },
    { key: 'DanhGiaNangLucKinhNghiem', label: 'Đánh giá năng lực kinh nghiệm' },
    { key: 'DanhGiaKyThuat', label: 'Đánh giá kỹ thuật' },
    { key: 'XepHangCuaNhaThauDoiChieu', label: 'Xếp hạng nhà thầu đối chiếu' },
    { key: 'KetQuaThuongThaoHopDong', label: 'Kết quả thương thảo hợp đồng' },
    { key: 'DanhSachNhaThauBiLoai', label: 'Danh sách nhà thầu bị loại' },
    { key: 'LyDoNhaThauBiLoai', label: 'Lý do nhà thầu bị loại' },
    { key: 'TenNhaThauDeNghiTrungThau', label: 'Tên nhà thầu đề nghị trúng thầu' },
    { key: 'GiaDeNghiTrungThau', label: 'Giá đề nghị trúng thầu', type: 'money' },
    { key: 'ThoiGianThucHienHD', label: 'Thời gian thực hiện hợp đồng' },
    { key: 'NhanXetTinhCanhTranhCongBangMinhBach', label: 'Nhận xét tính cạnh tranh, công bằng, minh bạch', type: 'textarea' },
    { key: 'NoiDungHSMTChuaPhuHopVaBienPhapXuLy', label: 'Nội dung HSMT chưa phù hợp và biện pháp xử lý' },
    { key: 'ThoiGianDangTaiKHLCNT', label: 'Thời gian đăng tải KHLCNT' },
    { key: 'ThoiGianDangTaiTBMTVaPhatHanhHSMT', label: 'Thời gian đăng tải TBMT và phát hành HSMT' },
    { key: 'ThoiGianLamRoHSMT', label: 'Thời gian làm rõ HSMT' },
    { key: 'ThoiGianSuaDoiEHSMT', label: 'Thời gian sửa đổi e-HSMT' },
    { key: 'ThoiDiemDongThau', label: 'Thời điểm đóng thầu', type: 'date' },
    { key: 'ThoiGianMoThau', label: 'Thời gian mở thầu' },
    { key: 'CacVanDeKhacKhiMoThau', label: 'Các vấn đề khác khi mở thầu' },
    { key: 'ThoiGianDanhGiaHSDT', label: 'Thời gian đánh giá HSDT' },
    { key: 'XuLyTinhHuongTrongDanhGia', label: 'Xử lý tình huống trong đánh giá' },
    { key: 'NhaThauVuotQuaKyThuat', label: 'Nhà thầu vượt qua kỹ thuật' },
    { key: 'YKienBenMoiThauVeBaoCao', label: 'Ý kiến bên mời thầu về báo cáo' },
    { key: 'NhanXetTinhMinhBachCuaBenMoiThau', label: 'Nhận xét tính minh bạch của bên mời thầu' },
    { key: 'KetQuaDoiChieuTaiLieu', label: 'Kết quả đối chiếu tài liệu' },
    { key: 'VanDePhatSinhKhiDoiChieu', label: 'Vấn đề phát sinh khi đối chiếu' },
    { key: 'QuaTrinhThuongThaoHopDong', label: 'Quá trình thương thảo hợp đồng' },
    { key: 'TenNhaThau', label: 'Tên nhà thầu' },
    { key: 'TenChuDauTu', label: 'Tên chủ đầu tư' },
    { key: 'TenNhaThauTrungThau', label: 'Tên nhà thầu trúng thầu' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu' },
    { key: 'GiaDuThau', label: 'Giá dự thầu', type: 'money' },
    { key: 'GiaDuThauSauHieuChinh', label: 'Giá dự thầu sau hiệu chỉnh', type: 'money' },
    { key: 'GiaTrungThau', label: 'Giá trúng thầu', type: 'money' },
    { key: 'ThoiGianThucHienHopDong', label: 'Thời gian thực hiện hợp đồng' },
    { key: 'NoiDungKhacCuaNhaThauTrungThau', label: 'Nội dung khác của nhà thầu trúng thầu' },
    { key: 'NhaThauKhongTrungThau', label: 'Nhà thầu không trúng thầu' },
    { key: 'TenDonViTrinh', label: 'Tên đơn vị trình' },
    { key: 'ChucDanhNguoiKy', label: 'Chức danh người ký' },
    { key: 'HoVaTenNguoiKy', label: 'Họ và tên người ký' },
  ],
  quyet_dinh_lcnt: [
    { key: 'ChuDauTu', label: 'Chủ đầu tư' },
    { key: 'TenGoiThau', label: 'Tên gói thầu' },
    { key: 'TenKeHoachLuaChonNhaThau', label: 'Tên kế hoạch lựa chọn nhà thầu' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện theo pháp luật của chủ đầu tư' },
    { key: 'SoTBMT', label: 'Số thông báo mời thầu' },
    { key: 'SoGoiThau', label: 'Số gói thầu' },
    { key: 'GiaGoiThauBangSo', label: 'Giá gói thầu bằng số', type: 'money' },
    { key: 'GiaGoiThauBangChu', label: 'Giá gói thầu bằng chữ', type: 'money-words' },
    { key: 'HinhThucLuaChonNhaThau', label: 'Hình thức lựa chọn nhà thầu' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng' },
    { key: 'ThoiGianThucHienGoiThau', label: 'Thời gian thực hiện gói thầu' },
    { key: 'TenNhaThauTrungThau', label: 'Tên nhà thầu trúng thầu' },
    { key: 'NhaThauTrungThau', label: 'Nhà thầu trúng thầu' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu' },
    { key: 'GiaDuThau', label: 'Giá dự thầu', type: 'money' },
    { key: 'GiaDuThauSauHieuChinh', label: 'Giá dự thầu sau hiệu chỉnh', type: 'money' },
    { key: 'DiemKyThuat', label: 'Điểm kỹ thuật' },
    { key: 'GiaDanhGia', label: 'Giá đánh giá', type: 'money' },
    { key: 'GiaTrungThau', label: 'Giá trúng thầu', type: 'money' },
    { key: 'ThoiGianThucHienHD', label: 'Thời gian thực hiện hợp đồng' },
    { key: 'NoiDungKhac', label: 'Nội dung khác' },
    { key: 'NhaThauKhongTrungThau', label: 'Nhà thầu không trúng thầu' },
    { key: 'PhanLoNhaThauThamDu', label: 'Phần/lô nhà thầu tham dự' },
    { key: 'LydoKhongTrungThau', label: 'Lý do không trúng thầu' },
    { key: 'TenCacVanBanPhapLyLienQuan', label: 'Tên các văn bản pháp lý liên quan', type: 'textarea' },
    { key: 'TenQuyetDinhPheDuyetKeHoachLuaChonNhaThau', label: 'Tên quyết định phê duyệt KHLCNT' },
    { key: 'DonViDuocGiao', label: 'Đơn vị được giao' },
    { key: 'VietTatNoiLuuVanBan', label: 'Viết tắt nơi lưu văn bản' },
    { key: 'ChucVuDaiDienChuDauTu', label: 'Chức vụ đại diện chủ đầu tư' },
  ],
  hop_dong: [
    { key: 'DiaDanh', label: 'Địa danh', group: 'chung' },
    { key: 'MaSoHD', label: 'Mã số hợp đồng', group: 'chung' },
    { key: 'ThoiGianKyHĐ', label: 'Thời gian ký hợp đồng', type: 'date', group: 'chung' },
    { key: 'NamKyHD', label: 'Năm ký hợp đồng', group: 'chung' },
    { key: 'TenGoiThau', label: 'Tên gói thầu', group: 'chung' },
    { key: 'TenDuAn', label: 'Tên dự án/dự toán mua sắm', group: 'chung' },
    { key: 'ChuDauTu', label: 'Chủ đầu tư', group: 'cdt' },
    { key: 'NhaThau', label: 'Nhà thầu', group: 'nt' },
    { key: 'TenQuyetDinhPheDuyetKeHoachLuaChonNhaThau', label: 'Tên quyết định phê duyệt KHLCNT', group: 'chung' },
    { key: 'DaiDienChuDauTu', label: 'Đại diện chủ đầu tư', group: 'cdt' },
    { key: 'ChucVuDaiDienChuDauTu', label: 'Chức vụ đại diện chủ đầu tư', group: 'cdt' },
    { key: 'DiaChiChuDauTu', label: 'Địa chỉ chủ đầu tư', group: 'cdt' },
    { key: 'SoDienThoaiChuDauTu', label: 'Số điện thoại chủ đầu tư', group: 'cdt' },
    { key: 'SoTaiKhoanChuDauTu', label: 'Số tài khoản chủ đầu tư', group: 'cdt' },
    { key: 'NganHangChuDauTu', label: 'Ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaSoNganHangChuDauTu', label: 'Mã số ngân hàng chủ đầu tư', group: 'cdt' },
    { key: 'MaSoThueChuDauTu', label: 'Mã số thuế chủ đầu tư', group: 'cdt' },
    { key: 'DaiDienNhaThau', label: 'Đại diện nhà thầu', group: 'nt' },
    { key: 'ChucVuDaiDienNhaThau', label: 'Chức vụ đại diện nhà thầu', group: 'nt' },
    { key: 'DiaChiNhaThau', label: 'Địa chỉ nhà thầu', group: 'nt' },
    { key: 'SoDienThoaiNhaThau', label: 'Số điện thoại nhà thầu', group: 'nt' },
    { key: 'SoTaiKhoanNhaThau', label: 'Số tài khoản nhà thầu', group: 'nt' },
    { key: 'NganHangNhaThau', label: 'Ngân hàng nhà thầu', group: 'nt' },
    { key: 'MaSoNganHangNhaThau', label: 'Mã số ngân hàng nhà thầu', group: 'nt' },
    { key: 'MaSoThueNhaThau', label: 'Mã số thuế nhà thầu', group: 'nt' },
    { key: 'ThanhPhanHDVaThuTuUuTienPhapLy', label: 'Thành phần HĐ và thứ tự ưu tiên pháp lý', type: 'textarea', group: 'chung' },
    { key: 'LoaiHopDong', label: 'Loại hợp đồng', group: 'chung' },
    { key: 'GiaHDBangSo', label: 'Giá hợp đồng bằng số', type: 'money', group: 'chung' },
    { key: 'GiaHDBangChu', label: 'Giá hợp đồng bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'TongSoLuongInHD', label: 'Tổng số lượng in hợp đồng', group: 'chung' },
    { key: 'SoLuongHDCuaChuDauTu', label: 'Số lượng HĐ của chủ đầu tư', group: 'cdt' },
    { key: 'SoLuongHDCuaNhaThau', label: 'Số lượng HĐ của nhà thầu', group: 'nt' },
    { key: 'ThoiGianThucHienHD', label: 'Thời gian thực hiện hợp đồng', group: 'chung' },
    { key: 'HieuLucHD', label: 'Hiệu lực hợp đồng', group: 'chung' },
    { key: 'GiaTriBaoDamThucHienHD', label: 'Giá trị bảo đảm thực hiện HĐ', type: 'money', group: 'chung' },
    { key: 'ThoiHanNopBaoDam', label: 'Thời hạn nộp bảo đảm', type: 'date', group: 'chung' },
    { key: 'TyLePhanTramBaoDam', label: 'Tỷ lệ phần trăm bảo đảm', group: 'chung' },
    { key: 'SoTienBaoDamBangSo', label: 'Số tiền bảo đảm bằng số', type: 'money', group: 'chung' },
    { key: 'SoTienBaoDamBangChu', label: 'Số tiền bảo đảm bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'ThoiHanHoanTraBaoDam', label: 'Thời hạn hoàn trả bảo đảm', type: 'date', group: 'chung' },
    { key: 'DanhSachNhaThauPhu', label: 'Danh sách nhà thầu phụ', group: 'nt' },
    { key: 'ThoiHanDeTrinhToaAn', label: 'Thời hạn đệ trình tòa án', group: 'chung' },
    { key: 'DanhSachChungTuCungCap', label: 'Danh sách chứng từ cung cấp', type: 'textarea', group: 'chung' },
    { key: 'TongGiaTriHopDongBangSo', label: 'Tổng giá trị hợp đồng bằng số', type: 'money', group: 'chung' },
    { key: 'TongGiaTriHopDongBangChu', label: 'Tổng giá trị hợp đồng bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'TamUng', label: 'Tạm ứng', type: 'money', group: 'chung' },
    { key: 'ThanhToan', label: 'Thanh toán', group: 'chung' },
    { key: 'TyLeThanhToan', label: 'Tỷ lệ thanh toán', group: 'chung' },
    { key: 'SoTienThanhToanBangSo', label: 'Số tiền thanh toán bằng số', type: 'money', group: 'chung' },
    { key: 'SoTienThanhToanBangChu', label: 'Số tiền thanh toán bằng chữ', type: 'money-words', group: 'chung' },
    { key: 'HoSoThanhToan', label: 'Hồ sơ thanh toán', type: 'textarea', group: 'chung' },
    { key: 'ThoiHanThanhToan', label: 'Thời hạn thanh toán', type: 'date', group: 'chung' },
    { key: 'BaoHanh', label: 'Bảo hành', group: 'chung' },
    { key: 'DongGoiHangHoa', label: 'Đóng gói hàng hoá', group: 'chung' },
    { key: 'CacDichVuBaoGom', label: 'Các dịch vụ bao gồm', group: 'chung' },
    { key: 'KiemTraThuNghiemHangHoa', label: 'Kiểm tra thử nghiệm hàng hoá', group: 'chung' },
    { key: 'DiaDiemKiemTraThuNghiem', label: 'Địa điểm kiểm tra thử nghiệm', group: 'chung' },
    { key: 'SoTienPhatViPhamHD', label: 'Số tiền phạt vi phạm HĐ', type: 'money', group: 'chung' },
    { key: 'TyLePhatMoiTuan', label: 'Tỷ lệ phạt mỗi tuần', group: 'chung' },
    { key: 'MucPhatToiDa', label: 'Mức phạt tối đa', type: 'money', group: 'chung' },
    { key: 'BoiThuongThietHai', label: 'Bồi thường thiệt hại', group: 'chung' },
    { key: 'ThoiHanBaoHanh', label: 'Thời hạn bảo hành', group: 'chung' },
    { key: 'DiaDiemBaoHanh', label: 'Địa điểm bảo hành', group: 'chung' },
    { key: 'ThoiHanSuaChuaKhacPhuc', label: 'Thời hạn sửa chữa khắc phục', group: 'chung' },
    { key: 'ThoiHanCuThe', label: 'Thời hạn cụ thể', group: 'chung' },
    { key: 'TyLeThanhToanTietKiem', label: 'Tỷ lệ thanh toán tiết kiệm', group: 'chung' },
  ],
};

export const ATTACHMENT_ONLY = new Set([
  'cong_van_tham_gia', 'thong_tin_to_chuyen_gia', 'san_pham_hsmt',
  'bao_cao_tham_dinh_hsmt', 'dang_tai_hsmt', 'bao_cao_danh_gia_hsdt',
  'bien_ban_doi_chieu', 'bao_cao_tham_dinh_kqlcnt', 'dang_tai_lcnt',
]);

export function getFieldsForStep(stepKey: string, procurementMethod: string): FieldDef[] {
  if (procurementMethod === 'CHI_DINH_THAU') return CDT_STEP_FIELDS[stepKey] || [];
  return CHCT_STEP_FIELDS[stepKey] || [];
}

export function hasDocxTemplate(stepKey: string): boolean {
  return !ATTACHMENT_ONLY.has(stepKey);
}
